[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
aptPkgs = [
 "chromium",
 "chromium-driver",
 "libnss3",
 "libxss1",
 "libasound2",
 "libatk1.0-0",
 "libatk-bridge2.0-0",
 "libcups2",
 "libgbm1",
 "libxshmfence1",
 "libx11-xcb1",
 "libxcb1",
 "fonts-noto-cjk",
]

[build.nixpacksPlan.phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[build.nixpacksPlan.phases.build]
cmds = ["pnpm build:selenium-worker"]

[deploy]
startCommand = "pnpm start:selenium-worker"
